config/routes.rb
Mangnolia::Application.routes.draw do
  
  root :to => 'questionnaires#notice'
  resources :users
  resources :questionnaires
  match 'notice' => 'questionnaires#notice', :as => :notice
  match 'signup' => 'users#new', :as => :signup, :via => [:get]
  match 'signin' => 'sessions#new', :as => :signin, :via => [:get]
  match 'signin' => 'sessions#create', :as => :signin, :via => [:post]
  match 'signout' => 'sessions#destroy', :as => :signout
  

end

app/models/questionnaire.rb
# -*- encoding : utf-8 -*-
class Questionnaire < ActiveRecord::Base
  
  validates :holistic_estimation, presence: true
  validates :answer_1, presence: true
  validates :answer_2, presence: true
  validates :answer_3, presence: true
end

app/models/test.rb
# -*- encoding : utf-8 -*-
class Test < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  has_secure_password
  has_one :questionnaire
  
  validates :email, presence: true, uniqueness: true, length: { maximum: 50 }, email_format: { :message => '不是有效的' }
  validates :name, presence: true, length: { maximum: 100 }
  validates :gender, presence: true
  validates :occupation, presence: true
  validates :confucius_institute, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  
  protected
  def authenticate
    redirect_to signin_path if session[:user].blank?
  end
end

app/controllers/questionnaires_controller.rb
# -*- encoding : utf-8 -*-
class QuestionnairesController < ApplicationController
  
  def new
    @questionnaire = Questionnaire.new
  end
  
  def edit
    @questionnaire = Questionnaire.find(params[:id])
  end
  
  def create
    @questionnaire = Questionnaire.new(params[:questionnaire])
    @questionnaire.user_id = session[:user][:id]
    if @questionnaire.save
      redirect_to notice_path, notice: '调查表填写完成！'
    else
      render action: "new"
    end
  end
  
  def update
    @questionnaire = Questionnaire.find(params[:id])
    if @questionnaire.update_attributes(params[:questionnaire])
      redirect_to notice_path, notice: '调查表修改完成！'
    else
      render action: "edit"
    end
  end
  
  def notice
    @questionnaire = Questionnaire.where(user_id: session[:user][:id]).first
  end
end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController
  skip_before_filter :authenticate

  def new
    
  end
  
  def create
    user = User.where(email: params[:email]).first.try(:authenticate, params[:password])
    unless user.blank?
      user.update_attribute :last_signined_at, user.current_signined_at
      user.update_attribute :current_signined_at, Time.now
      session[:user] = { id: user.id, name: user.name, last_signined_at: user.last_signined_at }
      redirect_to notice_path
    else
      redirect_to signin_path, :alert => '用户名或密码错误！'
    end
  end

  def destroy
    reset_session
    redirect_to signin_path
  end
end

app/controllers/tests_controller.rb
# -*- encoding : utf-8 -*-
class TestsController < ApplicationController
  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tests }
    end
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
    @test = Test.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/new
  # GET /tests/new.json
  def new
    @test = Test.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test }
    end
  end

  # GET /tests/1/edit
  def edit
    @test = Test.find(params[:id])
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(params[:test])

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render json: @test, status: :created, location: @test }
      else
        format.html { render action: "new" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tests/1
  # PUT /tests/1.json
  def update
    @test = Test.find(params[:id])

    respond_to do |format|
      if @test.update_attributes(params[:test])
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test = Test.find(params[:id])
    @test.destroy

    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :authenticate, :only => [:new, :create]
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      @user.update_attribute :current_signined_at, Time.now
      session[:user] = { id: @user.id, name: @user.name, last_signined_at: @user.last_signined_at }
      redirect_to notice_path, notice: '注册成功！'
    else
      render action: "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  
  def flash_tag
    if flash[:alert]
      content_tag 'p', h(flash[:alert]), class: 'notice alert'
    elsif flash[:notice]
      content_tag 'p', h(flash[:notice]), class: 'notice'
    end
  end
end

app/helpers/tests_helper.rb
# -*- encoding : utf-8 -*-
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>党的群众路线教育实践活动调查问卷</title>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div id="header"></div>
		<div id="main">
			<div id="content">
				<%= yield %>
			</div>
		</div>
		<div id="footer">
			<p>主办：国家汉办 地址：北京市西城区德胜门外大街129号</p>
		</div>
	</div>
</body>
</html>

app/views/questionnaires/edit.html.erb
<%= form_for @questionnaire do |f| %>
	<%= render 'shared/error_messages', target: @questionnaire %>
	<fieldset class="questionnaire generic-form">
		<ul>
			<li><label>国家汉办作风情况总体评价：</label><%= f.radio_button :holistic_estimation, 1 %>好 <%= f.radio_button :holistic_estimation, 2 %>较好 <%= f.radio_button :holistic_estimation, 3 %>一般 <%= f.radio_button :holistic_estimation, 4 %>差</li>
		</ul>
		<ul>
			<li><label>国家汉办在形式主义、官僚主义、享乐主义、奢靡之风方面存在哪些突出问题：</label><%= f.text_area :answer_1, :class => 'text-area' %></li>
		</ul>
		<ul>
			<li><label>对国家汉办进一步加强作风建设、改进为广大汉语教师志愿者服务方面的意见建议：</label><%= f.text_area :answer_2, :class => 'text-area' %></li>
		</ul>
		<ul>
			<li><label>对贯彻落实《孔子学院发展规划（2012-2020）》，办好孔子学院方面的意见建议：</label><%= f.text_area :answer_3, :class => 'text-area' %></li>
		</ul>
	</fieldset>
	<div class="action">
		<%= link_to image_tag('btn_submit.png', :alt => '提交'), '#', :onclick => "submitForm('edit_questionnaire_#{@questionnaire.id}')", :class => 'button' %>
	</div>
<% end %>

app/views/questionnaires/new.html.erb
<%= form_for @questionnaire do |f| %>
	<%= render 'shared/error_messages', target: @questionnaire %>
	<fieldset class="questionnaire generic-form">
		<ul>
			<li><label>国家汉办作风情况总体评价：</label><%= f.radio_button :holistic_estimation, 1 %>好 <%= f.radio_button :holistic_estimation, 2 %>较好 <%= f.radio_button :holistic_estimation, 3 %>一般 <%= f.radio_button :holistic_estimation, 4 %>差</li>
		</ul>
		<ul>
			<li><label>国家汉办在形式主义、官僚主义、享乐主义、奢靡之风方面存在哪些突出问题：</label><%= f.text_area :answer_1, :class => 'text-area' %></li>
		</ul>
		<ul>
			<li><label>对国家汉办进一步加强作风建设、改进为广大汉语教师志愿者服务方面的意见建议：</label><%= f.text_area :answer_2, :class => 'text-area' %></li>
		</ul>
		<ul>
			<li><label>对贯彻落实《孔子学院发展规划（2012-2020）》，办好孔子学院方面的意见建议：</label><%= f.text_area :answer_3, :class => 'text-area' %></li>
		</ul>
	</fieldset>
	<div class="action">
		<%= link_to image_tag('btn_submit.png', :alt => '提交'), '#', :onclick => "submitForm('new_questionnaire')", :class => 'button' %>
	</div>
<% end %>

app/views/questionnaires/notice.html.erb
<%= flash_tag %>
<div class="notice">
	<h1>关于征求对国家汉办作风建设意见的通知</h1>
	<p>各孔子学院中方院长、教师和志愿者：</p>
	<p>　　衷心感谢您为孔子学院建设所付出的辛勤努力和做出的重要贡献！根据教育部关于深入开展党的群众路线教育实践活动的统一部署，为广泛深入听取对汉办和汉办领导班子的意见建议，找准突出问题，明确整改重点，确保教育实践活动取得实效，现就以下问题征求意见：</p>
	<p>　　一、国家汉办作风建设的总体情况如何？在形式主义、官僚主义、享乐主义、奢靡之风方面存在哪些突出问题？</p>
	<p>　　二、对我办进一步加强作风建设、改进为广大汉语教师志愿者服务方面有什么意见建议？</p>
	<p>　　三、关于贯彻落实《孔子学院发展规划（2012-2020年）》，办好孔子学院方面有什么意见建议？</p>
	<p>　　请于8月10日前，将《国家汉办作风情况调查表》反馈给国家汉办党委办公室。</p>
	<p class="button">
		<% if @questionnaire.blank? %>
			<%= link_to image_tag('btn_questionnaire.png'), new_questionnaire_path %>
		<% else %>
			<%= link_to image_tag('btn_questionnaire.png'), edit_questionnaire_path(@questionnaire) %>
		<% end %>
		<%= link_to image_tag('btn_signout.png'), signout_path %>
	</p>
	<p>&nbsp;</p>
	<p>　　谢谢您的热情参与！</p>
	<p>&nbsp;</p>
	<p class="sign">孔子学院总部/国家汉办</p>
	<p class="sign">2013年7月20日</p>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2>发生了<%= target.errors.count %>个错误：</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, html: { id: 'signup' } do |f| %>
	<%= render 'shared/error_messages', target: @user %>
	<fieldset class="signup generic-form">
		<legend><%= image_tag 'ico_signup.png' %></legend>
		<ul>
			<li><label>邮箱：</label><%= f.text_field :email, :class => 'text-field' %></li>
		</ul>
		<ul>
			<li><label>密码：</label><%= f.password_field :password, :class => 'text-field' %></li>
		</ul>
		<ul>
			<li><label>确认密码：</label><%= f.password_field :password_confirmation, :class => 'text-field' %></li>
		</ul>
		<ul>
			<li><label>姓名：</label><%= f.text_field :name, :class => 'text-field' %></li>
		</ul>
		<ul>
			<li><label>性别：</label><%= f.radio_button :gender, 1 %>男 <%= f.radio_button :gender, 2 %>女</li>
		</ul>
		<ul>
			<li><label>职业：</label><%= f.radio_button :occupation, 1 %>教师 <%= f.radio_button :occupation, 2 %>志愿者 <%= f.radio_button :occupation, 3 %>院长</li>
		</ul>
		<ul>
			<li><label>所属孔院：</label><%= f.text_field :confucius_institute, :class => 'text-field' %></li>
		</ul>
	</fieldset>
	<div class="action">
		<%= link_to image_tag('btn_submit.png', :alt => '提交'), '#', :onclick => "submitForm('signup')", :class => 'button' %>
		<%= link_to image_tag('btn_signin.png', :alt => '登录'), signin_path, :class => 'button' %>
	</div>
<% end %>